-- ============================================================
-- Libreria San Martin - Esquema PostgreSQL / Supabase
-- Generado automaticamente desde el esquema MySQL (MariaDB 10.4)
-- Proyecto: tkypdjfmifywnwwjmcfh
-- Tablas: 32
-- ============================================================

set client_encoding = 'UTF8';
set search_path = public;


CREATE TABLE IF NOT EXISTS "auditoria" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_categorias" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_clientes" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accion" varchar(255) DEFAULT NULL,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_compras" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_inventario" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_productos" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_proveedores" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_usuarios" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "auditoria_ventas" (
  "id_auditoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "accion" text,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "caja_flujo" (
  "id_caja" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "monto_apertura" numeric(10,2),
  "monto_cierre" numeric(10,2) DEFAULT NULL,
  "fecha_apertura" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_cierre" timestamp without time zone DEFAULT NULL,
  "estado" varchar(20) DEFAULT 'ABIERTA',
  CONSTRAINT "caja_flujo_estado_ck" CHECK (estado IN ('ABIERTA','CERRADA'))
);

CREATE TABLE IF NOT EXISTS "categorias" (
  "id_categoria" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_categoria" varchar(100) DEFAULT NULL,
  "codigo_categoria" varchar(20) DEFAULT NULL,
  "icono" varchar(50) DEFAULT 'bi-tags-fill',
  "categoria_padre" integer DEFAULT NULL,
  "activo" smallint DEFAULT 1,
  "visible_tienda" smallint DEFAULT 1,
  "descripcion" text DEFAULT NULL,
  "orden" integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "clientes" (
  "id_cliente" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ci_nit" varchar(20),
  "fecha_nacimiento" date DEFAULT NULL,
  "nombre_cliente" varchar(100),
  "telefono" varchar(20) DEFAULT NULL,
  "email" varchar(100) DEFAULT NULL,
  "fecha_registro" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "activo" smallint DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "gastos" (
  "id_gasto" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(255),
  "monto" numeric(10,2),
  "fecha" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "id_usuario" integer
);

CREATE TABLE IF NOT EXISTS "movimientos_inventario" (
  "id_movimiento" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer,
  "tipo" varchar(20),
  "cantidad" integer,
  "motivo" varchar(255) DEFAULT NULL,
  "id_usuario" integer DEFAULT NULL,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "proveedores" (
  "id_proveedor" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) DEFAULT NULL,
  "telefono" varchar(30) DEFAULT NULL,
  "direccion" varchar(255) DEFAULT NULL,
  "activo" smallint DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "sucursales" (
  "id_sucursal" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "direccion" text DEFAULT NULL,
  "telefono" varchar(20) DEFAULT NULL,
  "activo" smallint DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "usuarios" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) DEFAULT NULL,
  "usuario" varchar(50) DEFAULT NULL,
  "rol" varchar(30) DEFAULT NULL,
  "estado" varchar(20) DEFAULT 'Activo',
  "imagen" varchar(255) DEFAULT NULL,
  "foto" varchar(255) DEFAULT NULL,
  "firma" text DEFAULT NULL,
  "fecha_registro" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "ultimo_acceso" timestamp without time zone DEFAULT NULL,
  "tema" varchar(10) DEFAULT 'light'
);

CREATE TABLE IF NOT EXISTS "ventas" (
  "id_venta" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date DEFAULT NULL,
  "total" numeric(10,2) DEFAULT NULL,
  "metodo_pago" varchar(50) DEFAULT NULL,
  "id_usuario" integer DEFAULT NULL,
  "id_cliente" integer DEFAULT NULL,
  "estado" varchar(20) DEFAULT 'Completado'
);

CREATE TABLE IF NOT EXISTS "apertura_caja" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "fecha_apertura" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_cierre" timestamp without time zone DEFAULT NULL,
  "monto_inicial" numeric(10,2) DEFAULT 0.00,
  "monto_esperado" numeric(10,2) DEFAULT NULL,
  "monto_final" numeric(10,2) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "activo" smallint DEFAULT 1,
  CONSTRAINT "apertura_caja_ibfk_1" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id")
);

CREATE TABLE IF NOT EXISTS "compras" (
  "id_compra" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proveedor_id" integer DEFAULT NULL,
  "nro_factura" varchar(50) DEFAULT NULL,
  "fecha" date DEFAULT NULL,
  "total" numeric(10,2) DEFAULT NULL,
  CONSTRAINT "compras_ibfk_1" FOREIGN KEY ("proveedor_id") REFERENCES "proveedores" ("id_proveedor")
);

CREATE TABLE IF NOT EXISTS "config_impresora" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer,
  "tipo" varchar(20) DEFAULT 'ticket',
  "ancho" integer DEFAULT 80,
  "charset" varchar(20) DEFAULT 'UTF-8',
  CONSTRAINT "config_impresora_ibfk_1" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id")
);

CREATE TABLE IF NOT EXISTS "devoluciones" (
  "id_devolucion" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_venta" integer,
  "id_usuario" integer,
  "fecha" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "motivo" text DEFAULT NULL,
  "total_devuelto" numeric(10,2) DEFAULT 0.00,
  CONSTRAINT "devoluciones_ibfk_1" FOREIGN KEY ("id_venta") REFERENCES "ventas" ("id_venta"),
  CONSTRAINT "devoluciones_ibfk_2" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id")
);

CREATE TABLE IF NOT EXISTS "mensajes_chat" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_remitente" integer,
  "id_destinatario" integer DEFAULT NULL,
  "mensaje" text,
  "leido" smallint DEFAULT 0,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "mensajes_chat_ibfk_1" FOREIGN KEY ("id_remitente") REFERENCES "usuarios" ("id"),
  CONSTRAINT "mensajes_chat_ibfk_2" FOREIGN KEY ("id_destinatario") REFERENCES "usuarios" ("id")
);

CREATE TABLE IF NOT EXISTS "pedidos" (
  "id_pedido" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "cliente_nombre" varchar(150),
  "cliente_telefono" varchar(20) DEFAULT NULL,
  "sucursal_id" integer DEFAULT NULL,
  "metodo_pago" varchar(50) DEFAULT 'Efectivo',
  "estado" varchar(30) DEFAULT 'Pendiente',
  "total" numeric(10,2),
  "codigo_seguimiento" varchar(20) DEFAULT NULL,
  "notas" text DEFAULT NULL,
  "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pedidos_codigo_seguimiento_key" UNIQUE ("codigo_seguimiento"),
  CONSTRAINT "pedidos_ibfk_1" FOREIGN KEY ("sucursal_id") REFERENCES "sucursales" ("id_sucursal") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "productos" (
  "id_producto" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(20),
  "codigo_barras" varchar(50) DEFAULT NULL,
  "nombre_producto" varchar(150) DEFAULT NULL,
  "descripcion" text DEFAULT NULL,
  "precio" numeric(10,2) DEFAULT NULL,
  "precio_compra" numeric(10,2) DEFAULT 0.00,
  "impuesto" numeric(5,2) DEFAULT 0.00,
  "talla" varchar(20) DEFAULT NULL,
  "color" varchar(50) DEFAULT NULL,
  "stock" integer DEFAULT NULL,
  "imagen" varchar(255) DEFAULT NULL,
  "activo" smallint DEFAULT 1,
  "categoria_id" integer DEFAULT NULL,
  CONSTRAINT "productos_ibfk_1" FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id_categoria")
);

CREATE TABLE IF NOT EXISTS "recibos" (
  "id_recibo" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venta_id" integer,
  "numero_recibo" varchar(20),
  "fecha_emision" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "recibos_numero_recibo_key" UNIQUE ("numero_recibo"),
  CONSTRAINT "recibos_ibfk_1" FOREIGN KEY ("venta_id") REFERENCES "ventas" ("id_venta") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "detalle_compras" (
  "id_detalle" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compra_id" integer DEFAULT NULL,
  "producto_id" integer DEFAULT NULL,
  "cantidad" integer DEFAULT NULL,
  "precio" numeric(10,2) DEFAULT NULL,
  CONSTRAINT "detalle_compras_ibfk_1" FOREIGN KEY ("compra_id") REFERENCES "compras" ("id_compra"),
  CONSTRAINT "detalle_compras_ibfk_2" FOREIGN KEY ("producto_id") REFERENCES "productos" ("id_producto")
);

CREATE TABLE IF NOT EXISTS "detalle_devoluciones" (
  "id_detalle" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_devolucion" integer,
  "id_producto" integer,
  "cantidad" integer,
  "precio_unitario" numeric(10,2),
  "subtotal" numeric(10,2),
  CONSTRAINT "detalle_devoluciones_ibfk_1" FOREIGN KEY ("id_devolucion") REFERENCES "devoluciones" ("id_devolucion"),
  CONSTRAINT "detalle_devoluciones_ibfk_2" FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto")
);

CREATE TABLE IF NOT EXISTS "detalle_pedidos" (
  "id_detalle" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" integer,
  "producto_id" integer,
  "cantidad" integer,
  "precio" numeric(10,2),
  CONSTRAINT "detalle_pedidos_ibfk_1" FOREIGN KEY ("pedido_id") REFERENCES "pedidos" ("id_pedido") ON DELETE CASCADE,
  CONSTRAINT "detalle_pedidos_ibfk_2" FOREIGN KEY ("producto_id") REFERENCES "productos" ("id_producto")
);

CREATE TABLE IF NOT EXISTS "detalle_ventas" (
  "id_detalle" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venta_id" integer DEFAULT NULL,
  "producto_id" integer DEFAULT NULL,
  "cantidad" integer DEFAULT NULL,
  "precio" numeric(10,2) DEFAULT NULL,
  CONSTRAINT "detalle_ventas_ibfk_1" FOREIGN KEY ("venta_id") REFERENCES "ventas" ("id_venta"),
  CONSTRAINT "detalle_ventas_ibfk_2" FOREIGN KEY ("producto_id") REFERENCES "productos" ("id_producto")
);

CREATE TABLE IF NOT EXISTS "historial_precios" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer,
  "precio_anterior" numeric(10,2),
  "precio_nuevo" numeric(10,2),
  "tipo" varchar(20) DEFAULT 'venta',
  "id_usuario" integer DEFAULT NULL,
  "fecha_hora" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "historial_precios_ibfk_1" FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto"),
  CONSTRAINT "historial_precios_ibfk_2" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id")
);

CREATE INDEX IF NOT EXISTS "id_usuario" ON "apertura_caja" ("id_usuario");
CREATE INDEX IF NOT EXISTS "proveedor_id" ON "compras" ("proveedor_id");
CREATE INDEX IF NOT EXISTS "id_usuario" ON "config_impresora" ("id_usuario");
CREATE INDEX IF NOT EXISTS "id_venta" ON "devoluciones" ("id_venta");
CREATE INDEX IF NOT EXISTS "id_usuario" ON "devoluciones" ("id_usuario");
CREATE INDEX IF NOT EXISTS "id_remitente" ON "mensajes_chat" ("id_remitente");
CREATE INDEX IF NOT EXISTS "id_destinatario" ON "mensajes_chat" ("id_destinatario");
CREATE INDEX IF NOT EXISTS "sucursal_id" ON "pedidos" ("sucursal_id");
CREATE INDEX IF NOT EXISTS "categoria_id" ON "productos" ("categoria_id");
CREATE INDEX IF NOT EXISTS "venta_id" ON "recibos" ("venta_id");
CREATE INDEX IF NOT EXISTS "compra_id" ON "detalle_compras" ("compra_id");
CREATE INDEX IF NOT EXISTS "producto_id" ON "detalle_compras" ("producto_id");
CREATE INDEX IF NOT EXISTS "id_devolucion" ON "detalle_devoluciones" ("id_devolucion");
CREATE INDEX IF NOT EXISTS "id_producto" ON "detalle_devoluciones" ("id_producto");
CREATE INDEX IF NOT EXISTS "pedido_id" ON "detalle_pedidos" ("pedido_id");
CREATE INDEX IF NOT EXISTS "producto_id" ON "detalle_pedidos" ("producto_id");
CREATE INDEX IF NOT EXISTS "venta_id" ON "detalle_ventas" ("venta_id");
CREATE INDEX IF NOT EXISTS "producto_id" ON "detalle_ventas" ("producto_id");
CREATE INDEX IF NOT EXISTS "id_producto" ON "historial_precios" ("id_producto");
CREATE INDEX IF NOT EXISTS "id_usuario" ON "historial_precios" ("id_usuario");

-- ============================================================================
-- SECUENCIAS: alineadas con MAX(id) + 1 en todas las columnas identity.
-- Si se resetean a MAX(id) con is_called=false, el siguiente INSERT choca
-- con la clave primaria existente ("duplicate key value violates unique
-- constraint"). Este bloque es idempotente y se recalcula siempre.
-- ============================================================================
DO $sync_seq$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.table_name, c.column_name,
           pg_get_serial_sequence(format('public.%I', c.table_name), c.column_name) AS seq
      FROM information_schema.columns c
     WHERE c.table_schema = 'public'
       AND c.is_identity = 'YES'
  LOOP
    IF r.seq IS NOT NULL THEN
      EXECUTE format(
        'SELECT setval(%L, GREATEST(COALESCE((SELECT MAX(%I) FROM public.%I), 0) + 1, 1), false)',
        r.seq, r.column_name, r.table_name);
    END IF;
  END LOOP;
END
$sync_seq$;
